version: '3.7'

services:
  data_base_sam:
    image: postgres
    container_name: data_base_sam
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_pinnacle-station
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
